swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger petstore
  description: A sample API that demonstrates Swagger-Express-Middleware features

consumes:
  - application/json
produces:
  - application/json

definitions:
  pet:
    required:
      - name
      - type
    properties:
      name:
        type: string
        minLength: 4
        pattern: "^[a-zA-Z0-9- ]+$"
      age:
        type: integer
      dob:
        type: string
        format: 'date'
      type:
        type: string
        enum: [cat, dog, bird]
      address:
        $ref: "#/definitions/address"
      vet:
        $ref: "#/definitions/veterinarian"
      tags:
        type: array
        uniqueItems: true
        items:
          type: string
          minLength: 1

  veterinarian:
    required:
      - name
    properties:
      name:
        type: string
        minLength: 1
      address:
        $ref: "#/definitions/address"

  address:
    properties:
      street:
        type: string
        minLength: 1
      city:
        type: string
        minLength: 1
      state:
        type: string
        minLength: 2
        maxLength: 2
        pattern: "^[A-Z]+$"
      zipcode:
        type: integer
        minimum: 10000
        maximum: 99999

parameters:
  petName:
    name: petName
    in: path
    description: Name of the pet
    required: true
    type: string

paths: