INSERT INTO university_study(`year`,name,member) values('	104	','	探討十大死因時空群聚及共位之變遷分析','廖冠豪、何維涓、彭紹宇、陳文慈'	);
INSERT INTO university_study(`year`,name,member) values('	103	','	基於醫療物聯網概念建置醫院雲端資訊服務-以身高體重計與血壓計為例	','呂凱煜、魏志軒、施宜涵、葉晉江');
INSERT INTO university_study(`year`,name,member) values('	102	','	監控影像之液面高度判釋研究','張皓威、李國華、蔡伊婷	');
INSERT INTO university_study(`year`,name,member) values('	102	',' Android鼾聲檢測系統開發	','周柏汶、許峻榮、陳日陞 、劉倢妤'	);
INSERT INTO university_study(`year`,name,member) values('	101	','	結合二維條碼與行動平台之用藥安全輔助系統','康嘉佑、宋星賢');
INSERT INTO university_study(`year`,name,member) values('	101	','	改良血氧濃度特徵指摽進行阻塞型睡眠呼吸暫止症預測','陳諭葶、魏千琛'	);
INSERT INTO university_study(`year`,name,member) values('	100	','	結合QR Code與擴增實境於用藥安全輔助系統之開發',	'陳佳妤、劉家豪	');
INSERT INTO university_study(`year`,name,member) values('	100	','	ECG個人健康紀錄管理系統雛型開發:以Android平台為例','蔡宗諭、沈瑜豐、廖芳彬');
INSERT INTO university_study(`year`,name,member) values('	99	','	U化情境運算之應用-以健康照護及電力監測為例	','謝欣翰、林俊汶');
INSERT INTO university_study(`year`,name,member) values('	98	',' 老人照護管理系統之開發','陳韻?、劉嘉琪、黃詩涵、彭詩婷');
INSERT INTO university_study(`year`,name,member) values('	97	','	演化式計算於分群演算法之改良探討(以乳癌診斷為應用例)','周書妤、古怡芳、劉軒豪、吳荏維');
INSERT INTO university_study(`year`,name,member) values('	96	','	Hire Management System (HMS)租借管理系統－以Video租借為例','蔡峻榮、吳君孝');
INSERT INTO university_study(`year`,name,member) values('	96	','	智慧型疾病診斷輔助系統之研發以肝炎及心血管疾病為例	','李宜亭、王瀅茜');
INSERT INTO university_study(`year`,name,member) values('	95	','	智慧型圖書館虛擬管理員系統	','簡宜庭、張彙音、王乃宣');